/*
 * Admin.java
 *
 * Created on __DATE__, __TIME__
 */

package com.design;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import com.actions.Action;
import com.actions.AdminReceive;
import com.multicast.MulticastRx;

/**
 * 
 * @author __USER__
 */
public class Admin extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Action action;

	/** Creates new form Admin */
	public Admin() {
		initComponents();
		init();
	}

	private void init() {
		// TODO Auto-generated method stub
		action = new Action();
		action.loadFiles(jtaDB);
		new AdminReceive(this);
		new MulticastRx(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jtaDB = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		txtBW = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		tbl = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		jtaMDC = new javax.swing.JTextArea();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jtaPeers = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jLabel1.setText("Media DB :");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(20, 40, 130, 16);

		jtaDB.setColumns(20);
		jtaDB.setRows(5);
		jScrollPane1.setViewportView(jtaDB);

		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(20, 60, 190, 170);

		jLabel2.setText("Admin Bandwidth:");
		getContentPane().add(jLabel2);
		jLabel2.setBounds(220, 10, 110, 20);
		getContentPane().add(txtBW);
		txtBW.setBounds(330, 10, 140, 22);

		jLabel3.setText("Requested Users:");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(220, 40, 120, 16);

		dft = new DefaultTableModel();
		tbl.setModel(dft);
		jScrollPane2.setViewportView(tbl);
		dft.addColumn("Peer Name");
		dft.addColumn("Port");
		dft.addColumn("Band Width");
		dft.addColumn("Req.File");

		getContentPane().add(jScrollPane2);
		jScrollPane2.setBounds(220, 60, 390, 170);

		jtaMDC.setColumns(20);
		jtaMDC.setRows(5);
		jScrollPane3.setViewportView(jtaMDC);

		getContentPane().add(jScrollPane3);
		jScrollPane3.setBounds(220, 260, 390, 220);

		jLabel4.setText("MDC :");
		getContentPane().add(jLabel4);
		jLabel4.setBounds(220, 240, 190, 16);

		jLabel5.setText("Available Peers:");
		getContentPane().add(jLabel5);
		jLabel5.setBounds(20, 240, 150, 16);

		jtaPeers.setColumns(20);
		jtaPeers.setRows(5);
		jScrollPane4.setViewportView(jtaPeers);

		getContentPane().add(jScrollPane4);
		jScrollPane4.setBounds(20, 260, 190, 220);

		setSize(650, 537);
		setTitle("Admin::");
		setResizable(false);
		setVisible(true);
	}// </editor-fold>

	// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			UIManager
					.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch (Exception e) {
			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Admin().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	public javax.swing.JTextArea jtaDB;
	public javax.swing.JTextArea jtaMDC;
	public javax.swing.JTextArea jtaPeers;
	private javax.swing.JTable tbl;
	private javax.swing.JTextField txtBW;
	public DefaultTableModel dft;
	// End of variables declaration//GEN-END:variables

}