/*
 * User.java
 *
 * Created on __DATE__, __TIME__
 */

package com.design;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import com.actions.Action;
import com.actions.UserReceive;
import com.multicast.MulticastTx;

/**
 * 
 * @author __USER__
 */
public class User extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Action action;
	public String source;
	int port;
	int bw;
	UserReceive ur;

	/** Creates new form User */
	public User() {
		initComponents();
		action = new Action();
		init();
	}

	private void init() {
		source = action.getSource();
		setTitle(source);
		bw = action.getBW();
		jLabel2.setText("" + bw);
		port = action.getPort();
		action.setProperty("SCPorts.properties", source, "" + port);
		ur = new UserReceive(this, port);
		new MulticastTx(source);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtReqFile = new javax.swing.JTextField();
		btnREQ = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		btnPlay = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		panelPly = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jLabel1.setText("Band Width:");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(20, 20, 60, 14);

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
		getContentPane().add(jLabel2);
		jLabel2.setBounds(80, 20, 110, 14);

		jLabel3.setText("Enter REQ File:");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(20, 50, 80, 14);
		getContentPane().add(txtReqFile);
		txtReqFile.setBounds(100, 50, 370, 20);

		btnREQ.setText("Request");
		btnREQ.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnREQActionPerformed(evt);
			}
		});
		getContentPane().add(btnREQ);
		btnREQ.setBounds(100, 80, 110, 23);

		jLabel4.setText("Received Status:");
		getContentPane().add(jLabel4);
		jLabel4.setBounds(20, 100, 190, 14);

		btnPlay.setText("Play Received File");
		btnPlay.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPlayActionPerformed(evt);
			}
		});
		getContentPane().add(btnPlay);
		btnPlay.setBounds(20, 360, 120, 30);

		dft = new DefaultTableModel();
		jTable1.setModel(dft);
		jScrollPane1.setViewportView(jTable1);
		dft.addColumn("MDC Descriptions");
		dft.addColumn("File Name");
		getContentPane().add(jScrollPane1);
		jScrollPane1.setBounds(20, 120, 452, 130);

		panelPly.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Video Player"));
		panelPly.setLayout(null);
		getContentPane().add(panelPly);
		panelPly.setBounds(150, 260, 320, 220);

		setSize(500, 537);
		setResizable(false);
		setVisible(true);
	}// </editor-fold>

	// GEN-END:initComponents

	private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		action.mediaPlayer(ur.lrecFile.getAbsolutePath(), panelPly);

	}

	private void btnREQActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		action.sendREQ(source, jLabel2.getText(), port, txtReqFile.getText());
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			UIManager
					.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch (Exception e) {
			e.printStackTrace();
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new User().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnPlay;
	private javax.swing.JButton btnREQ;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JPanel panelPly;
	private javax.swing.JTextField txtReqFile;
	public DefaultTableModel dft;
	// End of variables declaration//GEN-END:variables

}